# sort()
list1=[12,3,4,5,6,7,8]
print("*************sort()*********************")
list1.sort() # if we print this it will return None as it sorts the actual list and doesnot return new list
print(list1)

print("************reverse()**********************")
list1.reverse() # revrses the list
print(list1)
print("**************appends()********************")
list1.append(2134) # append at the end of the list
print(list1)
print("***************insert()*******************")
list1.insert(0,1) # used to insert at the perticular index
print(list1)
print("****************pop()******************")
list1.pop(1) # remove the element from the mentioned index
print(list1)
print("***************remove()*******************")
list1.remove(1) # remove value 12 from the list
print(list1)
print("**********************************")
